const priceListFieldKeys = {
  category1: [
    "fuelFilterReplacement",
    "airFilterReplacement",
    "cabinFilterReplacement",
    "oilChange",
    "manualTransmissionOilChange",
    "automaticTransmissionOilChange",
    "clutchReplacement",
    "gearboxReplacement",
    "shockAbsorberReplacement",
    "wishboneReplacement",
    "wishboneBushingReplacement",
    "stabilizerLinkReplacement",
    "frontAndRearStabilizerRubberReplacement",
    "rearBeamRubberReplacement",
    "wheelHubReplacement",
    "inner/outerCVJointBootReplacement",
    "suspensionDiagnostics",
    "powerSteeringFluidReplacement",
    "steeringTieRodEndReplacement",
    "steeringRodReplacement",
    "coolantReplacement",
    "radiatorReplacement (cleaning)",
    "heaterCoreReplacement",
    "timingBeltReplacement",
    "chainTimingReplacement",
    "engineReplacement",
    "valveCoverGasketReplacement",
    "manifoldGasketReplacement",
    "headGasketReplacement",
    "multi-VBeltReplacement",
    "beltWithRollersReplacement",
    "camshaftPositionSensorReplacement",
    "frontCrankshaftSensorReplacement",
    "brakeFluidReplacement",
    "padReplacement",
    "discWithPadsReplacementFront/rear",
    "brakeHoseReplacement",
    "brakeCaliperReplacement",
  ],
  electricalRepair: [
    "computerDiagnostics",
    "batteryReplacement",
    "bulbReplacement",
    "starterReplacement/regeneration",
    "alternatorReplacement/regeneration",
    "fuseReplacement",
    "turnSignalAndWiperSwitchRepair",
    "dashboardDisassembly/assembly",
    "sparkPlugReplacement",
    "aBS /ESPRepair",
    "sparkPlugReplacementPerPiece",
    "glowPlugReplacementPerPiece",
    "lockRepair",
    "sideWindowReplacement",
  ],
  tireService: [
    "wheelReplacement",
    "tireReplacementWithBalancing",
    "wheelBalancing",
  ],
};

export default priceListFieldKeys;